#!/bin/bash

cd *

#read location of the start-up script

read LOC

echo "Checking if the testing plugin exists"

ls -l m10k_test_plugin 2 > /dev/null

#look for test plugin
if [ "$?" == 2 ]
	then
		echo "$0" plugin not found"
		exit 2
	fi


#if plugin exists then run it
#pass location of startup script as STDIN

./m10k_test_plugin <<< $LOC

exit 0
