#!/usr/bin/python
# Parse the config file

import csv, sys, os
filename = "monkeys10k-se.config"

try:
	# Open file
	f = open(os.path.join(sys.path[0], filename), 'r')
except IOError:
	print "Can't open", filename
	sys.exit(1)
else:
	# Read file
	reader = csv.reader(f, delimiter=' ')
	
	# Output
	for line in reader:
		for option in line:
			print option.rsplit(':', 1)[-1],
		sys.stdout.write('|')

		for option in line:
			print '-fno-' + option.rsplit(':', 1)[-1][2:],
		print
	print
 
	f.close()
	sys.exit(0)
