#!/bin/bash
#By Yehoshua Ghitis

# Goes into project directorry
cd *
read PERMUTATION

# Set FLAGS to the options from permutation
export CFLAGS="$PERMUTATION"

./configure --prefix=$HOME/.m10k/build

make
make install

#echo "m10k_build"
#ls -l m10k_build_plugin 2> /dev/null
#if [ "$?" == 2 ]
#then
#    echo "$0: File not found"
#    exit 2
#fi
#./m10k_build_plugin <<< echo $*


exit 0
