#!/bin/bash
#m10k_build_plugin test file

# Unpack source
tar xf gzip*t*z

# Goes into project directorry
cd gzip-[0-9]*

# Read configuration to be tested
read PERMUTATION

# Set FLAGS to the options from permutation
export CFLAGS="$PERMUTATION"

./configure || exit $?

make -j8


